array(11) {
  ["id"]=>
  string(26) "form_alter_field_node_mail"
  ["module"]=>
  string(16) "form_alter_field"
  ["key"]=>
  string(9) "node_mail"
  ["to"]=>
  string(22) "kksasteph888@gmail.com"
  ["from"]=>
  string(19) "contact@o-de-mer.fr"
  ["language"]=>
  object(stdClass)#6 (12) {
    ["language"]=>
    string(2) "fr"
    ["name"]=>
    string(6) "French"
    ["native"]=>
    string(9) "Français"
    ["direction"]=>
    string(1) "0"
    ["enabled"]=>
    string(1) "1"
    ["plurals"]=>
    string(1) "2"
    ["formula"]=>
    string(6) "($n>1)"
    ["domain"]=>
    string(0) ""
    ["prefix"]=>
    string(2) "fr"
    ["weight"]=>
    string(1) "0"
    ["javascript"]=>
    string(43) "6BVajxD2L3PAfMcKhrXLdd5mLf91FWZEfPQkNkXZVQU"
    ["provider"]=>
    string(16) "language-default"
  }
  ["params"]=>
  array(4) {
    ["body"]=>
    string(157) "<h3> contenu du message </h3> 	
	<table>
		<tr>
			<td> Nom : </td>
			<td>vide</td>
		</tr>
		<tr>
			<td> Tél : </td>
			<td>vide</td>
		</tr>
	</table>
	"
    ["subject"]=>
    string(26) "Nouveau patient identifier"
    ["Sender"]=>
    string(11) "Synergi-Bio"
    ["Return-Path"]=>
    string(19) "contact@o-de-mer.fr"
  }
  ["send"]=>
  bool(true)
  ["subject"]=>
  string(26) "Nouveau patient identifier"
  ["body"]=>
  array(1) {
    [0]=>
    string(157) "<h3> contenu du message </h3> 	
	<table>
		<tr>
			<td> Nom : </td>
			<td>vide</td>
		</tr>
		<tr>
			<td> Tél : </td>
			<td>vide</td>
		</tr>
	</table>
	"
  }
  ["headers"]=>
  array(7) {
    ["MIME-Version"]=>
    string(3) "1.0"
    ["Content-Type"]=>
    string(24) "text/html; charset=utf-8"
    ["Content-Transfer-Encoding"]=>
    string(4) "8Bit"
    ["X-Mailer"]=>
    string(6) "Drupal"
    ["Return-Path"]=>
    string(19) "contact@o-de-mer.fr"
    ["Sender"]=>
    string(11) "Synergi-Bio"
    ["From"]=>
    string(35) ""Synergi-Bio" <contact@o-de-mer.fr>"
  }
}
