array(11) {
  ["id"]=>
  string(17) "contact_page_copy"
  ["module"]=>
  string(7) "contact"
  ["key"]=>
  string(9) "page_copy"
  ["to"]=>
  string(22) "kksasteph888@gmail.com"
  ["from"]=>
  string(22) "kksasteph888@gmail.com"
  ["language"]=>
  object(stdClass)#6 (12) {
    ["language"]=>
    string(2) "fr"
    ["name"]=>
    string(6) "French"
    ["native"]=>
    string(9) "Français"
    ["direction"]=>
    string(1) "0"
    ["enabled"]=>
    string(1) "1"
    ["plurals"]=>
    string(1) "2"
    ["formula"]=>
    string(6) "($n>1)"
    ["domain"]=>
    string(0) ""
    ["prefix"]=>
    string(2) "fr"
    ["weight"]=>
    string(1) "0"
    ["javascript"]=>
    string(43) "6BVajxD2L3PAfMcKhrXLdd5mLf91FWZEfPQkNkXZVQU"
    ["provider"]=>
    string(16) "language-default"
  }
  ["params"]=>
  array(13) {
    ["name"]=>
    string(8) "admin888"
    ["mail"]=>
    string(22) "kksasteph888@gmail.com"
    ["subject"]=>
    string(5) "essai"
    ["cid"]=>
    string(1) "1"
    ["message"]=>
    string(9) "iètiçè"
    ["copy"]=>
    int(1)
    ["submit"]=>
    string(18) "Envoyer le message"
    ["form_build_id"]=>
    string(48) "form-Sp6KthiBLSb4f8nDdBYqOu4uxjlsrjXjMhIA_V1_v4Q"
    ["form_token"]=>
    string(43) "Pyh7XwKBUuuOt0J6lxACFhJuOqJB89lmZm5SfbcHW4I"
    ["form_id"]=>
    string(17) "contact_site_form"
    ["op"]=>
    string(18) "Envoyer le message"
    ["sender"]=>
    object(stdClass)#83 (23) {
      ["uid"]=>
      string(1) "1"
      ["name"]=>
      string(8) "admin888"
      ["pass"]=>
      string(55) "$S$DYKrxDN8e/IFsgMOtrdXrG28C5.lGH4NcnJvd9WNAVwk1wUQBGPz"
      ["mail"]=>
      string(22) "kksasteph888@gmail.com"
      ["theme"]=>
      string(0) ""
      ["signature"]=>
      string(0) ""
      ["signature_format"]=>
      NULL
      ["created"]=>
      string(10) "1493029088"
      ["access"]=>
      string(10) "1513362123"
      ["login"]=>
      string(10) "1513276588"
      ["status"]=>
      string(1) "1"
      ["timezone"]=>
      string(18) "Africa/Brazzaville"
      ["language"]=>
      string(0) ""
      ["picture"]=>
      string(1) "0"
      ["init"]=>
      string(22) "kksasteph888@gmail.com"
      ["data"]=>
      bool(false)
      ["sid"]=>
      string(43) "I0KzHZJOlvAWywl_9XYJBavXpAs-zcPfdJ3MHyf5yTk"
      ["ssid"]=>
      string(0) ""
      ["hostname"]=>
      string(12) "41.202.207.5"
      ["timestamp"]=>
      string(10) "1513362158"
      ["cache"]=>
      string(1) "0"
      ["session"]=>
      string(119) "batches|a:9:{i:76;b:1;i:77;b:1;i:78;b:1;i:79;b:1;i:80;b:1;i:81;b:1;i:82;b:1;i:83;b:1;i:84;b:1;}updates_remaining|a:0:{}"
      ["roles"]=>
      array(2) {
        [2]=>
        string(18) "authenticated user"
        [3]=>
        string(13) "administrator"
      }
    }
    ["category"]=>
    array(6) {
      ["cid"]=>
      string(1) "1"
      ["category"]=>
      string(16) "Website feedback"
      ["recipients"]=>
      string(22) "kksasteph888@gmail.com"
      ["reply"]=>
      string(0) ""
      ["weight"]=>
      string(1) "0"
      ["selected"]=>
      string(1) "1"
    }
  }
  ["send"]=>
  bool(true)
  ["subject"]=>
  string(24) "[Website feedback] essai"
  ["body"]=>
  array(2) {
    [0]=>
    string(141) "admin888 (http://www.o-de-mer.fr/user/1) a envoyé un message en utilisant le formulaire de contact suivant : http://www.o-de-mer.fr/contact."
    [1]=>
    string(9) "iètiçè"
  }
  ["headers"]=>
  array(7) {
    ["MIME-Version"]=>
    string(3) "1.0"
    ["Content-Type"]=>
    string(51) "text/plain; charset=UTF-8; format=flowed; delsp=yes"
    ["Content-Transfer-Encoding"]=>
    string(4) "8Bit"
    ["X-Mailer"]=>
    string(6) "Drupal"
    ["Return-Path"]=>
    string(19) "contact@o-de-mer.fr"
    ["Sender"]=>
    string(19) "contact@o-de-mer.fr"
    ["From"]=>
    string(22) "kksasteph888@gmail.com"
  }
}
