array(11) {
  ["id"]=>
  string(20) "update_status_notify"
  ["module"]=>
  string(6) "update"
  ["key"]=>
  string(13) "status_notify"
  ["to"]=>
  string(22) "kksasteph888@gmail.com"
  ["from"]=>
  string(19) "contact@o-de-mer.fr"
  ["language"]=>
  object(stdClass)#6 (13) {
    ["language"]=>
    string(2) "fr"
    ["name"]=>
    string(6) "French"
    ["native"]=>
    string(9) "Français"
    ["direction"]=>
    string(1) "0"
    ["enabled"]=>
    string(1) "1"
    ["plurals"]=>
    string(1) "2"
    ["formula"]=>
    string(6) "($n>1)"
    ["domain"]=>
    string(0) ""
    ["prefix"]=>
    string(2) "fr"
    ["weight"]=>
    string(1) "0"
    ["javascript"]=>
    string(43) "6BVajxD2L3PAfMcKhrXLdd5mLf91FWZEfPQkNkXZVQU"
    ["provider"]=>
    string(16) "language-default"
    ["dir"]=>
    string(3) "ltr"
  }
  ["params"]=>
  array(1) {
    ["core"]=>
    int(1)
  }
  ["send"]=>
  bool(true)
  ["subject"]=>
  string(51) "Nouvelle(s) version(s) disponible(s) pour Ô de mer"
  ["body"]=>
  array(3) {
    [0]=>
    string(168) "Une mise à jour de sécurité est disponible pour votre version de Drupal. Afin de garantir la sécurité de votre serveur, effectuez immédiatement la mise à jour !"
    [1]=>
    string(111) "Voir la page des mises à jour disponibles pour plus d'informations :
http://o-de-mer.fr/admin/reports/updates"
    [2]=>
    string(220) "Votre site est actuellement configuré pour envoyer ces courriels lorsqu'une mise à jour est disponible. Pour n'être prévenu que pour les mises à jour de sécurité, http://o-de-mer.fr/admin/reports/updates/settings."
  }
  ["headers"]=>
  array(7) {
    ["MIME-Version"]=>
    string(3) "1.0"
    ["Content-Type"]=>
    string(51) "text/plain; charset=UTF-8; format=flowed; delsp=yes"
    ["Content-Transfer-Encoding"]=>
    string(4) "8Bit"
    ["X-Mailer"]=>
    string(6) "Drupal"
    ["Return-Path"]=>
    string(19) "contact@o-de-mer.fr"
    ["Sender"]=>
    string(19) "contact@o-de-mer.fr"
    ["From"]=>
    string(19) "contact@o-de-mer.fr"
  }
}
