array(11) {
  ["id"]=>
  string(18) "webform_submission"
  ["module"]=>
  string(7) "webform"
  ["key"]=>
  string(10) "submission"
  ["to"]=>
  string(68) "contact@o-de-mer.fr, kksasteph888@gmail.com, stephanekouwa@gmail.com"
  ["from"]=>
  string(56) ""=?UTF-8?B?U2l0ZSDDlCBkZSBtZXI=?=" <contact@o-de-mer.fr>"
  ["language"]=>
  object(stdClass)#6 (12) {
    ["language"]=>
    string(2) "fr"
    ["name"]=>
    string(6) "French"
    ["native"]=>
    string(9) "Français"
    ["direction"]=>
    string(1) "0"
    ["enabled"]=>
    string(1) "1"
    ["plurals"]=>
    string(1) "2"
    ["formula"]=>
    string(6) "($n>1)"
    ["domain"]=>
    string(0) ""
    ["prefix"]=>
    string(2) "fr"
    ["weight"]=>
    string(1) "0"
    ["javascript"]=>
    string(43) "6BVajxD2L3PAfMcKhrXLdd5mLf91FWZEfPQkNkXZVQU"
    ["provider"]=>
    string(16) "language-default"
  }
  ["params"]=>
  array(9) {
    ["message"]=>
    string(1004) "<p><div class="webform-html-textarea"><div style="padding: 10px;border: 1px solid #eee;"><p style="padding: 0 0 5px 0; margin: 0;"><strong>3 nuits</strong> : du 21/12/2017 au 24/12/2017 : 210 € </p> <p style="padding: 0 0 5px 0; margin: 0;"> <strong>3 Adultes</strong>  : 30 €</p> <p style="padding: 0 0 5px 0; margin: 0;"><strong>2 Enfants plus de 2 ans (10 Euros)</strong> :  60 € </p> <p style="padding: 0 0 5px 0; margin: 0;"><strong>2 Enfants moins de 2 ans (gratuit)</strong> :  Gratuit  </p> <p style="padding: 5px 0 5px 0; margin: 0;"><strong>Petit-déjeuner du </strong> 22/12  : 4   <br><strong>Petit-déjeuner du </strong> 23/12  : 4   <br><strong>Petit-déjeuner du </strong> 24/12  : 4   <br></p><p style="padding: 10px 0px 5px 0; margin: 10px 0 0px 0;  font-size: +150%; border-top: 1px solid #ccc;"><strong>Total</strong> : 360 € </p> </div></div></p>
<p>Commentaires: RAS</p>
<p>
<strong>Contact</strong><br />
Stephane kouwa<br />
698 516 963<br />
kksasteph888@gmail.com
</p>


"
    ["subject"]=>
    string(23) "Demande de réservation"
    ["headers"]=>
    array(3) {
      ["X-Mailer"]=>
      string(27) "Drupal Webform (PHP/7.1.10)"
      ["Reply-To"]=>
      string(22) "kksasteph888@gmail.com"
      ["Content-Type"]=>
      string(24) "text/html; charset=UTF-8"
    }
    ["node"]=>
    object(stdClass)#245 (31) {
      ["vid"]=>
      string(2) "44"
      ["uid"]=>
      string(1) "1"
      ["title"]=>
      string(8) "reserver"
      ["log"]=>
      string(0) ""
      ["status"]=>
      string(1) "1"
      ["comment"]=>
      string(1) "1"
      ["promote"]=>
      string(1) "0"
      ["sticky"]=>
      string(1) "0"
      ["nid"]=>
      string(2) "44"
      ["type"]=>
      string(7) "webform"
      ["language"]=>
      string(2) "fr"
      ["created"]=>
      string(10) "1495787477"
      ["changed"]=>
      string(10) "1497541825"
      ["tnid"]=>
      string(1) "0"
      ["translate"]=>
      string(1) "0"
      ["revision_timestamp"]=>
      string(10) "1497541825"
      ["revision_uid"]=>
      string(2) "43"
      ["field_breve_description"]=>
      array(1) {
        ["und"]=>
        array(1) {
          [0]=>
          array(3) {
            ["value"]=>
            string(183) "<p>Nous avons bien reçu votre demande de réservation dont voici le détail.<br />
Nous la traiterons sous 24h.</p>

<p><strong>Cédric et Mathilde</strong></p>

<p>&nbsp;</p>
"
            ["format"]=>
            string(9) "full_html"
            ["safe_value"]=>
            string(171) "<p>Nous avons bien reçu votre demande de réservation dont voici le détail.<br />
Nous la traiterons sous 24h.</p>
<p><strong>Cédric et Mathilde</strong></p>
<p> </p>
"
          }
        }
      }
      ["rdf_mapping"]=>
      array(9) {
        ["rdftype"]=>
        array(2) {
          [0]=>
          string(9) "sioc:Item"
          [1]=>
          string(13) "foaf:Document"
        }
        ["title"]=>
        array(1) {
          ["predicates"]=>
          array(1) {
            [0]=>
            string(8) "dc:title"
          }
        }
        ["created"]=>
        array(3) {
          ["predicates"]=>
          array(2) {
            [0]=>
            string(7) "dc:date"
            [1]=>
            string(10) "dc:created"
          }
          ["datatype"]=>
          string(12) "xsd:dateTime"
          ["callback"]=>
          string(12) "date_iso8601"
        }
        ["changed"]=>
        array(3) {
          ["predicates"]=>
          array(1) {
            [0]=>
            string(11) "dc:modified"
          }
          ["datatype"]=>
          string(12) "xsd:dateTime"
          ["callback"]=>
          string(12) "date_iso8601"
        }
        ["body"]=>
        array(1) {
          ["predicates"]=>
          array(1) {
            [0]=>
            string(15) "content:encoded"
          }
        }
        ["uid"]=>
        array(2) {
          ["predicates"]=>
          array(1) {
            [0]=>
            string(16) "sioc:has_creator"
          }
          ["type"]=>
          string(3) "rel"
        }
        ["name"]=>
        array(1) {
          ["predicates"]=>
          array(1) {
            [0]=>
            string(9) "foaf:name"
          }
        }
        ["comment_count"]=>
        array(2) {
          ["predicates"]=>
          array(1) {
            [0]=>
            string(16) "sioc:num_replies"
          }
          ["datatype"]=>
          string(11) "xsd:integer"
        }
        ["last_activity"]=>
        array(3) {
          ["predicates"]=>
          array(1) {
            [0]=>
            string(23) "sioc:last_activity_date"
          }
          ["datatype"]=>
          string(12) "xsd:dateTime"
          ["callback"]=>
          string(12) "date_iso8601"
        }
      }
      ["path"]=>
      array(1) {
        ["pathauto"]=>
        string(1) "1"
      }
      ["webform"]=>
      array(35) {
        ["nid"]=>
        string(2) "44"
        ["next_serial"]=>
        string(3) "110"
        ["confirmation"]=>
        string(163) "<p>Merci pour votre demande de réservation.<br />
Nous la traitons dans les 24 heures et revenons vers vous.</p>

<p><strong>Cédric et Mathilde</strong></p>
"
        ["confirmation_format"]=>
        string(9) "full_html"
        ["redirect_url"]=>
        string(6) "<none>"
        ["status"]=>
        string(1) "1"
        ["block"]=>
        string(1) "0"
        ["allow_draft"]=>
        string(1) "0"
        ["auto_save"]=>
        string(1) "0"
        ["submit_notice"]=>
        string(1) "1"
        ["confidential"]=>
        string(1) "0"
        ["submit_text"]=>
        string(0) ""
        ["submit_limit"]=>
        string(2) "-1"
        ["submit_interval"]=>
        string(2) "-1"
        ["total_submit_limit"]=>
        string(2) "-1"
        ["total_submit_interval"]=>
        string(2) "-1"
        ["progressbar_bar"]=>
        string(1) "1"
        ["progressbar_page_number"]=>
        string(1) "0"
        ["progressbar_percent"]=>
        string(1) "0"
        ["progressbar_pagebreak_labels"]=>
        string(1) "1"
        ["progressbar_include_confirmation"]=>
        string(1) "1"
        ["progressbar_label_first"]=>
        string(6) "Début"
        ["progressbar_label_confirmation"]=>
        string(8) "Terminé"
        ["preview"]=>
        string(1) "0"
        ["preview_next_button_label"]=>
        string(0) ""
        ["preview_prev_button_label"]=>
        string(0) ""
        ["preview_title"]=>
        string(0) ""
        ["preview_message"]=>
        string(0) ""
        ["preview_message_format"]=>
        string(10) "texte_code"
        ["preview_excluded_components"]=>
        array(0) {
        }
        ["record_exists"]=>
        bool(true)
        ["roles"]=>
        array(2) {
          [0]=>
          string(1) "1"
          [1]=>
          string(1) "2"
        }
        ["emails"]=>
        array(2) {
          [1]=>
          array(14) {
            ["nid"]=>
            string(2) "44"
            ["eid"]=>
            string(1) "1"
            ["email"]=>
            string(66) "contact@o-de-mer.fr,kksasteph888@gmail.com,stephanekouwa@gmail.com"
            ["subject"]=>
            string(23) "Demande de réservation"
            ["from_name"]=>
            string(14) "Site Ô de mer"
            ["from_address"]=>
            string(19) "contact@o-de-mer.fr"
            ["template"]=>
            string(366) "<p>[submission:values:recapitulatif2]</p>
<p>Commentaires: [submission:values:setting_user:commentaires]</p>
<p>
<strong>Contact</strong><br />
[submission:values:information_personnelle:prenom] [submission:values:information_personnelle:nom]<br />
[submission:values:information_personnelle:telephone]<br />
[submission:values:information_personnelle:email]
</p>


"
            ["excluded_components"]=>
            array(0) {
            }
            ["html"]=>
            string(1) "1"
            ["attachments"]=>
            string(1) "0"
            ["exclude_empty"]=>
            string(1) "0"
            ["extra"]=>
            bool(false)
            ["status"]=>
            string(1) "1"
            ["reply_to"]=>
            string(1) "9"
          }
          [2]=>
          array(14) {
            ["nid"]=>
            string(2) "44"
            ["eid"]=>
            string(1) "2"
            ["email"]=>
            string(1) "9"
            ["subject"]=>
            string(44) "Votre demande de réservation chez Ô de mer"
            ["from_name"]=>
            string(7) "default"
            ["from_address"]=>
            string(19) "contact@o-de-mer.fr"
            ["template"]=>
            string(66) "[node:field_breve_description]
[submission:values:recapitulatif2]
"
            ["excluded_components"]=>
            array(0) {
            }
            ["html"]=>
            string(1) "1"
            ["attachments"]=>
            string(1) "0"
            ["exclude_empty"]=>
            string(1) "0"
            ["extra"]=>
            bool(false)
            ["status"]=>
            string(1) "1"
            ["reply_to"]=>
            string(7) "default"
          }
        }
        ["components"]=>
        array(16) {
          [14]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(2) "14"
            ["pid"]=>
            string(1) "0"
            ["form_key"]=>
            string(7) "periode"
            ["name"]=>
            string(7) "Periode"
            ["type"]=>
            string(8) "fieldset"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(7) {
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["css_classes"]=>
              string(0) ""
              ["title_display"]=>
              int(0)
              ["collapsible"]=>
              int(0)
              ["collapsed"]=>
              int(0)
              ["description"]=>
              string(0) ""
            }
            ["required"]=>
            string(1) "0"
            ["weight"]=>
            string(2) "16"
            ["page_num"]=>
            int(1)
          }
          [13]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(2) "13"
            ["pid"]=>
            string(2) "14"
            ["form_key"]=>
            string(13) "date_darriver"
            ["name"]=>
            string(15) "Date d'arrivée"
            ["type"]=>
            string(9) "textfield"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(16) {
              ["title_display"]=>
              string(6) "before"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["wrapper_classes"]=>
              string(0) ""
              ["css_classes"]=>
              string(0) ""
              ["width"]=>
              string(0) ""
              ["maxlength"]=>
              string(0) ""
              ["minlength"]=>
              string(0) ""
              ["field_prefix"]=>
              string(0) ""
              ["field_suffix"]=>
              string(0) ""
              ["disabled"]=>
              int(0)
              ["unique"]=>
              int(0)
              ["description"]=>
              string(0) ""
              ["placeholder"]=>
              string(0) ""
              ["attributes"]=>
              array(0) {
              }
              ["analysis"]=>
              bool(false)
            }
            ["required"]=>
            string(1) "1"
            ["weight"]=>
            string(2) "14"
            ["page_num"]=>
            int(1)
          }
          [12]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(2) "12"
            ["pid"]=>
            string(2) "14"
            ["form_key"]=>
            string(11) "date_depart"
            ["name"]=>
            string(15) "Date de départ"
            ["type"]=>
            string(9) "textfield"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(16) {
              ["title_display"]=>
              string(6) "before"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["wrapper_classes"]=>
              string(0) ""
              ["css_classes"]=>
              string(0) ""
              ["width"]=>
              string(0) ""
              ["maxlength"]=>
              string(0) ""
              ["minlength"]=>
              string(0) ""
              ["field_prefix"]=>
              string(0) ""
              ["field_suffix"]=>
              string(0) ""
              ["disabled"]=>
              int(0)
              ["unique"]=>
              int(0)
              ["description"]=>
              string(0) ""
              ["placeholder"]=>
              string(0) ""
              ["attributes"]=>
              array(0) {
              }
              ["analysis"]=>
              bool(false)
            }
            ["required"]=>
            string(1) "1"
            ["weight"]=>
            string(2) "16"
            ["page_num"]=>
            int(1)
          }
          [18]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(2) "18"
            ["pid"]=>
            string(1) "0"
            ["form_key"]=>
            string(12) "setting_user"
            ["name"]=>
            string(12) "setting user"
            ["type"]=>
            string(8) "fieldset"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(7) {
              ["title_display"]=>
              string(4) "none"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["css_classes"]=>
              string(0) ""
              ["collapsible"]=>
              int(0)
              ["collapsed"]=>
              int(0)
              ["description"]=>
              string(0) ""
            }
            ["required"]=>
            string(1) "0"
            ["weight"]=>
            string(2) "17"
            ["page_num"]=>
            int(1)
          }
          [1]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(1) "1"
            ["pid"]=>
            string(2) "18"
            ["form_key"]=>
            string(7) "adultes"
            ["name"]=>
            string(7) "Adultes"
            ["type"]=>
            string(6) "select"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(16) {
              ["items"]=>
              string(13) "1|1
2|2
3|3"
              ["multiple"]=>
              int(0)
              ["title_display"]=>
              string(6) "before"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["wrapper_classes"]=>
              string(0) ""
              ["css_classes"]=>
              string(19) "selectNombreAdultes"
              ["aslist"]=>
              int(1)
              ["empty_option"]=>
              string(0) ""
              ["optrand"]=>
              int(0)
              ["other_option"]=>
              NULL
              ["other_text"]=>
              string(8) "Autre..."
              ["description"]=>
              string(0) ""
              ["custom_keys"]=>
              bool(false)
              ["options_source"]=>
              string(0) ""
              ["analysis"]=>
              bool(true)
            }
            ["required"]=>
            string(1) "1"
            ["weight"]=>
            string(2) "18"
            ["page_num"]=>
            int(1)
          }
          [3]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(1) "3"
            ["pid"]=>
            string(2) "18"
            ["form_key"]=>
            string(27) "enfant_plus_de_3_ans_20euro"
            ["name"]=>
            string(32) "Enfants plus de 2 ans (10 euros)"
            ["type"]=>
            string(6) "select"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(16) {
              ["items"]=>
              string(8) "1|1
2|2"
              ["multiple"]=>
              int(0)
              ["title_display"]=>
              string(6) "before"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["wrapper_classes"]=>
              string(0) ""
              ["css_classes"]=>
              string(20) "selectNombreEnf2plus"
              ["aslist"]=>
              int(1)
              ["empty_option"]=>
              string(0) ""
              ["optrand"]=>
              int(0)
              ["other_option"]=>
              NULL
              ["other_text"]=>
              string(8) "Autre..."
              ["description"]=>
              string(0) ""
              ["custom_keys"]=>
              bool(false)
              ["options_source"]=>
              string(0) ""
              ["analysis"]=>
              bool(true)
            }
            ["required"]=>
            string(1) "0"
            ["weight"]=>
            string(2) "19"
            ["page_num"]=>
            int(1)
          }
          [2]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(1) "2"
            ["pid"]=>
            string(2) "18"
            ["form_key"]=>
            string(30) "enfant_moins_de_3_ans_10_euros"
            ["name"]=>
            string(32) "Enfants moins de 2 ans (gratuit)"
            ["type"]=>
            string(6) "select"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(16) {
              ["items"]=>
              string(8) "1|1
2|2"
              ["multiple"]=>
              int(0)
              ["title_display"]=>
              string(6) "before"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["wrapper_classes"]=>
              string(0) ""
              ["css_classes"]=>
              string(21) "selectNombreEnf2moins"
              ["aslist"]=>
              int(1)
              ["empty_option"]=>
              string(0) ""
              ["optrand"]=>
              int(0)
              ["other_option"]=>
              NULL
              ["other_text"]=>
              string(8) "Autre..."
              ["description"]=>
              string(0) ""
              ["custom_keys"]=>
              bool(false)
              ["options_source"]=>
              string(0) ""
              ["analysis"]=>
              bool(true)
            }
            ["required"]=>
            string(1) "0"
            ["weight"]=>
            string(2) "20"
            ["page_num"]=>
            int(1)
          }
          [4]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(1) "4"
            ["pid"]=>
            string(2) "18"
            ["form_key"]=>
            string(11) "date_global"
            ["name"]=>
            string(24) "calendrier (ne pas supp)"
            ["type"]=>
            string(4) "date"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(12) {
              ["title_display"]=>
              string(6) "before"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["wrapper_classes"]=>
              string(17) "element-invisible"
              ["start_date"]=>
              string(7) "0 years"
              ["timezone"]=>
              string(4) "user"
              ["exclude"]=>
              array(0) {
              }
              ["end_date"]=>
              string(8) "+2 years"
              ["year_textfield"]=>
              int(0)
              ["datepicker"]=>
              int(1)
              ["description"]=>
              string(0) ""
              ["analysis"]=>
              bool(false)
            }
            ["required"]=>
            string(1) "0"
            ["weight"]=>
            string(2) "21"
            ["page_num"]=>
            int(1)
          }
          [15]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(2) "15"
            ["pid"]=>
            string(2) "18"
            ["form_key"]=>
            string(12) "commentaires"
            ["name"]=>
            string(12) "Commentaires"
            ["type"]=>
            string(8) "textarea"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(13) {
              ["title_display"]=>
              string(6) "before"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["wrapper_classes"]=>
              string(0) ""
              ["css_classes"]=>
              string(0) ""
              ["placeholder"]=>
              string(132) "Précisez ici vos demandes particulières éventuelles. Pour les enfants nous pouvons préparer un lit parapluie et une chaise haute"
              ["cols"]=>
              string(0) ""
              ["rows"]=>
              string(0) ""
              ["resizable"]=>
              int(1)
              ["disabled"]=>
              int(0)
              ["description"]=>
              string(0) ""
              ["attributes"]=>
              array(0) {
              }
              ["analysis"]=>
              bool(false)
            }
            ["required"]=>
            string(1) "0"
            ["weight"]=>
            string(2) "22"
            ["page_num"]=>
            int(1)
          }
          [19]=>
          array(12) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(2) "19"
            ["pid"]=>
            string(1) "0"
            ["form_key"]=>
            string(14) "recapitulatif2"
            ["name"]=>
            string(13) "recapitulatif"
            ["type"]=>
            string(13) "html_textarea"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(15) {
              ["title_display"]=>
              string(6) "before"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["wrapper_classes"]=>
              string(0) ""
              ["css_classes"]=>
              string(0) ""
              ["format"]=>
              string(10) "texte_code"
              ["cols"]=>
              string(0) ""
              ["rows"]=>
              string(0) ""
              ["resizable"]=>
              int(1)
              ["disabled"]=>
              int(0)
              ["description"]=>
              string(0) ""
              ["attributes"]=>
              array(0) {
              }
              ["show_format_fieldset"]=>
              int(1)
              ["show_tips"]=>
              int(1)
              ["show_link"]=>
              int(1)
            }
            ["required"]=>
            string(1) "0"
            ["weight"]=>
            string(2) "19"
            ["mandatory"]=>
            int(0)
            ["page_num"]=>
            int(1)
          }
          [6]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(1) "6"
            ["pid"]=>
            string(1) "0"
            ["form_key"]=>
            string(23) "information_personnelle"
            ["name"]=>
            string(25) "Informations personnelles"
            ["type"]=>
            string(8) "fieldset"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(7) {
              ["description_above"]=>
              int(1)
              ["private"]=>
              int(0)
              ["css_classes"]=>
              string(0) ""
              ["title_display"]=>
              int(0)
              ["collapsible"]=>
              int(0)
              ["collapsed"]=>
              int(0)
              ["description"]=>
              string(0) ""
            }
            ["required"]=>
            string(1) "0"
            ["weight"]=>
            string(2) "20"
            ["page_num"]=>
            int(1)
          }
          [7]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(1) "7"
            ["pid"]=>
            string(1) "6"
            ["form_key"]=>
            string(3) "nom"
            ["name"]=>
            string(3) "Nom"
            ["type"]=>
            string(9) "textfield"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(16) {
              ["title_display"]=>
              string(6) "before"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["wrapper_classes"]=>
              string(0) ""
              ["css_classes"]=>
              string(0) ""
              ["width"]=>
              string(0) ""
              ["maxlength"]=>
              string(0) ""
              ["minlength"]=>
              string(0) ""
              ["field_prefix"]=>
              string(0) ""
              ["field_suffix"]=>
              string(0) ""
              ["disabled"]=>
              int(0)
              ["unique"]=>
              int(0)
              ["description"]=>
              string(0) ""
              ["placeholder"]=>
              string(0) ""
              ["attributes"]=>
              array(0) {
              }
              ["analysis"]=>
              bool(false)
            }
            ["required"]=>
            string(1) "1"
            ["weight"]=>
            string(1) "6"
            ["page_num"]=>
            int(1)
          }
          [8]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(1) "8"
            ["pid"]=>
            string(1) "6"
            ["form_key"]=>
            string(6) "prenom"
            ["name"]=>
            string(7) "Prénom"
            ["type"]=>
            string(9) "textfield"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(16) {
              ["title_display"]=>
              string(6) "before"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["wrapper_classes"]=>
              string(0) ""
              ["css_classes"]=>
              string(0) ""
              ["width"]=>
              string(0) ""
              ["maxlength"]=>
              string(0) ""
              ["minlength"]=>
              string(0) ""
              ["field_prefix"]=>
              string(0) ""
              ["field_suffix"]=>
              string(0) ""
              ["disabled"]=>
              int(0)
              ["unique"]=>
              int(0)
              ["description"]=>
              string(0) ""
              ["placeholder"]=>
              string(0) ""
              ["attributes"]=>
              array(0) {
              }
              ["analysis"]=>
              bool(false)
            }
            ["required"]=>
            string(1) "1"
            ["weight"]=>
            string(1) "7"
            ["page_num"]=>
            int(1)
          }
          [9]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(1) "9"
            ["pid"]=>
            string(1) "6"
            ["form_key"]=>
            string(5) "email"
            ["name"]=>
            string(5) "Email"
            ["type"]=>
            string(5) "email"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(14) {
              ["title_display"]=>
              string(6) "before"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["wrapper_classes"]=>
              string(0) ""
              ["css_classes"]=>
              string(0) ""
              ["multiple"]=>
              int(0)
              ["format"]=>
              string(5) "short"
              ["width"]=>
              string(0) ""
              ["unique"]=>
              int(0)
              ["disabled"]=>
              int(0)
              ["description"]=>
              string(0) ""
              ["placeholder"]=>
              string(0) ""
              ["attributes"]=>
              array(0) {
              }
              ["analysis"]=>
              bool(false)
            }
            ["required"]=>
            string(1) "1"
            ["weight"]=>
            string(1) "8"
            ["page_num"]=>
            int(1)
          }
          [10]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(2) "10"
            ["pid"]=>
            string(1) "6"
            ["form_key"]=>
            string(9) "telephone"
            ["name"]=>
            string(10) "Télephone"
            ["type"]=>
            string(9) "textfield"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(16) {
              ["title_display"]=>
              string(6) "before"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["wrapper_classes"]=>
              string(0) ""
              ["css_classes"]=>
              string(0) ""
              ["width"]=>
              string(0) ""
              ["maxlength"]=>
              string(0) ""
              ["minlength"]=>
              string(0) ""
              ["field_prefix"]=>
              string(0) ""
              ["field_suffix"]=>
              string(0) ""
              ["disabled"]=>
              int(0)
              ["unique"]=>
              int(0)
              ["description"]=>
              string(0) ""
              ["placeholder"]=>
              string(0) ""
              ["attributes"]=>
              array(0) {
              }
              ["analysis"]=>
              bool(false)
            }
            ["required"]=>
            string(1) "1"
            ["weight"]=>
            string(1) "9"
            ["page_num"]=>
            int(1)
          }
          [16]=>
          array(11) {
            ["nid"]=>
            int(44)
            ["cid"]=>
            string(2) "16"
            ["pid"]=>
            string(1) "0"
            ["form_key"]=>
            string(6) "option"
            ["name"]=>
            string(7) "option "
            ["type"]=>
            string(9) "textfield"
            ["value"]=>
            string(0) ""
            ["extra"]=>
            array(16) {
              ["title_display"]=>
              string(6) "before"
              ["description_above"]=>
              int(0)
              ["private"]=>
              int(0)
              ["wrapper_classes"]=>
              string(17) "element-invisible"
              ["css_classes"]=>
              string(0) ""
              ["width"]=>
              string(0) ""
              ["maxlength"]=>
              string(0) ""
              ["minlength"]=>
              string(0) ""
              ["field_prefix"]=>
              string(0) ""
              ["field_suffix"]=>
              string(0) ""
              ["disabled"]=>
              int(0)
              ["unique"]=>
              int(0)
              ["description"]=>
              string(0) ""
              ["placeholder"]=>
              string(0) ""
              ["attributes"]=>
              array(0) {
              }
              ["analysis"]=>
              bool(false)
            }
            ["required"]=>
            string(1) "0"
            ["weight"]=>
            string(2) "21"
            ["page_num"]=>
            int(1)
          }
        }
        ["conditionals"]=>
        array(0) {
        }
      }
      ["cid"]=>
      string(1) "0"
      ["last_comment_timestamp"]=>
      string(10) "1495787477"
      ["last_comment_name"]=>
      NULL
      ["last_comment_uid"]=>
      string(1) "1"
      ["comment_count"]=>
      string(1) "0"
      ["locations"]=>
      array(0) {
      }
      ["location"]=>
      array(0) {
      }
      ["name"]=>
      string(8) "admin888"
      ["picture"]=>
      string(1) "0"
      ["data"]=>
      string(4) "b:0;"
    }
    ["submission"]=>
    object(stdClass)#291 (13) {
      ["sid"]=>
      string(3) "163"
      ["nid"]=>
      string(2) "44"
      ["serial"]=>
      string(3) "110"
      ["uid"]=>
      string(1) "1"
      ["is_draft"]=>
      string(1) "0"
      ["highest_valid_page"]=>
      string(1) "0"
      ["submitted"]=>
      string(10) "1513362750"
      ["completed"]=>
      string(10) "1513362750"
      ["modified"]=>
      string(10) "1513362750"
      ["remote_addr"]=>
      string(12) "41.202.207.5"
      ["name"]=>
      string(8) "admin888"
      ["preview"]=>
      bool(false)
      ["data"]=>
      array(13) {
        [1]=>
        array(1) {
          [0]=>
          string(1) "3"
        }
        [2]=>
        array(1) {
          [0]=>
          string(1) "2"
        }
        [3]=>
        array(1) {
          [0]=>
          string(1) "2"
        }
        [4]=>
        array(1) {
          [0]=>
          string(0) ""
        }
        [7]=>
        array(1) {
          [0]=>
          string(5) "kouwa"
        }
        [8]=>
        array(1) {
          [0]=>
          string(8) "Stephane"
        }
        [9]=>
        array(1) {
          [0]=>
          string(22) "kksasteph888@gmail.com"
        }
        [10]=>
        array(1) {
          [0]=>
          string(11) "698 516 963"
        }
        [12]=>
        array(1) {
          [0]=>
          string(10) "24-12-2017"
        }
        [13]=>
        array(1) {
          [0]=>
          string(10) "21-12-2017"
        }
        [15]=>
        array(1) {
          [0]=>
          string(3) "RAS"
        }
        [16]=>
        array(1) {
          [0]=>
          string(0) ""
        }
        [19]=>
        array(1) {
          [0]=>
          string(826) "<div style="padding: 10px;border: 1px solid #eee;"><p style="padding: 0 0 5px 0; margin: 0;"><strong>3 nuits</strong> : du 21/12/2017 au 24/12/2017 : 210 € </p> <p style="padding: 0 0 5px 0; margin: 0;"> <strong>3 Adultes</strong>  : 30 €</p> <p style="padding: 0 0 5px 0; margin: 0;"><strong>2 Enfants plus de 2 ans (10 Euros)</strong> :  60 € </p> <p style="padding: 0 0 5px 0; margin: 0;"><strong>2 Enfants moins de 2 ans (gratuit)</strong> :  Gratuit  </p> <p style="padding: 5px 0 5px 0; margin: 0;"><strong>Petit-déjeuner du </strong> 22/12  : 4   <br><strong>Petit-déjeuner du </strong> 23/12  : 4   <br><strong>Petit-déjeuner du </strong> 24/12  : 4   <br></p><p style="padding: 10px 0px 5px 0; margin: 10px 0 0px 0;  font-size: +150%; border-top: 1px solid #ccc;"><strong>Total</strong> : 360 € </p> </div>"
        }
      }
    }
    ["email"]=>
    array(17) {
      ["nid"]=>
      string(2) "44"
      ["eid"]=>
      string(1) "1"
      ["email"]=>
      string(66) "contact@o-de-mer.fr,kksasteph888@gmail.com,stephanekouwa@gmail.com"
      ["subject"]=>
      string(23) "Demande de réservation"
      ["from_name"]=>
      string(14) "Site Ô de mer"
      ["from_address"]=>
      string(19) "contact@o-de-mer.fr"
      ["template"]=>
      string(366) "<p>[submission:values:recapitulatif2]</p>
<p>Commentaires: [submission:values:setting_user:commentaires]</p>
<p>
<strong>Contact</strong><br />
[submission:values:information_personnelle:prenom] [submission:values:information_personnelle:nom]<br />
[submission:values:information_personnelle:telephone]<br />
[submission:values:information_personnelle:email]
</p>


"
      ["excluded_components"]=>
      array(0) {
      }
      ["html"]=>
      bool(true)
      ["attachments"]=>
      string(1) "0"
      ["exclude_empty"]=>
      string(1) "0"
      ["extra"]=>
      bool(false)
      ["status"]=>
      string(1) "1"
      ["reply_to"]=>
      string(1) "9"
      ["message"]=>
      string(1004) "<p><div class="webform-html-textarea"><div style="padding: 10px;border: 1px solid #eee;"><p style="padding: 0 0 5px 0; margin: 0;"><strong>3 nuits</strong> : du 21/12/2017 au 24/12/2017 : 210 € </p> <p style="padding: 0 0 5px 0; margin: 0;"> <strong>3 Adultes</strong>  : 30 €</p> <p style="padding: 0 0 5px 0; margin: 0;"><strong>2 Enfants plus de 2 ans (10 Euros)</strong> :  60 € </p> <p style="padding: 0 0 5px 0; margin: 0;"><strong>2 Enfants moins de 2 ans (gratuit)</strong> :  Gratuit  </p> <p style="padding: 5px 0 5px 0; margin: 0;"><strong>Petit-déjeuner du </strong> 22/12  : 4   <br><strong>Petit-déjeuner du </strong> 23/12  : 4   <br><strong>Petit-déjeuner du </strong> 24/12  : 4   <br></p><p style="padding: 10px 0px 5px 0; margin: 10px 0 0px 0;  font-size: +150%; border-top: 1px solid #ccc;"><strong>Total</strong> : 360 € </p> </div></div></p>
<p>Commentaires: RAS</p>
<p>
<strong>Contact</strong><br />
Stephane kouwa<br />
698 516 963<br />
kksasteph888@gmail.com
</p>


"
      ["headers"]=>
      array(2) {
        ["X-Mailer"]=>
        string(27) "Drupal Webform (PHP/7.1.10)"
        ["Reply-To"]=>
        string(22) "kksasteph888@gmail.com"
      }
      ["from"]=>
      string(56) ""=?UTF-8?B?U2l0ZSDDlCBkZSBtZXI=?=" <contact@o-de-mer.fr>"
    }
    ["attachments"]=>
    array(0) {
    }
    ["plain"]=>
    bool(false)
    ["plaintext"]=>
    NULL
  }
  ["send"]=>
  bool(true)
  ["subject"]=>
  string(23) "Demande de réservation"
  ["body"]=>
  array(1) {
    [0]=>
    string(1004) "<p><div class="webform-html-textarea"><div style="padding: 10px;border: 1px solid #eee;"><p style="padding: 0 0 5px 0; margin: 0;"><strong>3 nuits</strong> : du 21/12/2017 au 24/12/2017 : 210 € </p> <p style="padding: 0 0 5px 0; margin: 0;"> <strong>3 Adultes</strong>  : 30 €</p> <p style="padding: 0 0 5px 0; margin: 0;"><strong>2 Enfants plus de 2 ans (10 Euros)</strong> :  60 € </p> <p style="padding: 0 0 5px 0; margin: 0;"><strong>2 Enfants moins de 2 ans (gratuit)</strong> :  Gratuit  </p> <p style="padding: 5px 0 5px 0; margin: 0;"><strong>Petit-déjeuner du </strong> 22/12  : 4   <br><strong>Petit-déjeuner du </strong> 23/12  : 4   <br><strong>Petit-déjeuner du </strong> 24/12  : 4   <br></p><p style="padding: 10px 0px 5px 0; margin: 10px 0 0px 0;  font-size: +150%; border-top: 1px solid #ccc;"><strong>Total</strong> : 360 € </p> </div></div></p>
<p>Commentaires: RAS</p>
<p>
<strong>Contact</strong><br />
Stephane kouwa<br />
698 516 963<br />
kksasteph888@gmail.com
</p>


"
  }
  ["headers"]=>
  array(8) {
    ["MIME-Version"]=>
    string(3) "1.0"
    ["Content-Type"]=>
    string(24) "text/html; charset=UTF-8"
    ["Content-Transfer-Encoding"]=>
    string(4) "8Bit"
    ["X-Mailer"]=>
    string(27) "Drupal Webform (PHP/7.1.10)"
    ["Return-Path"]=>
    string(19) "contact@o-de-mer.fr"
    ["Sender"]=>
    string(19) "contact@o-de-mer.fr"
    ["From"]=>
    string(56) ""=?UTF-8?B?U2l0ZSDDlCBkZSBtZXI=?=" <contact@o-de-mer.fr>"
    ["Reply-To"]=>
    string(22) "kksasteph888@gmail.com"
  }
}
